### PR TITLE
 1143.LongestCommonSubsequence.cpp

### PR DESCRIPTION
**Pull request by sahaniaditya**
Added 1143.LongestCommonSubsequence.cpp

### CODE REVIEW

**Comment by frostbyte012** [comment]
Update the README.md file as well.

**Comment by frostbyte012** [comment]
Also add code comments for the better reference.

**Comment by frostbyte012** [comment]
Confirm solving the merge conflict issue and check for it if it arrives.

**Comment by sahaniaditya** [comment]
Ok sir.

**Comment by frostbyte012** [comment]
Make sure u close all the previous branches as well before finally merging.

**Review by frostbyte012 — COMMENTED** [review]
Add comment sections.

**Pull request closed without merging**
